### ISSUE TITLE
Doesn't change Playnite to fullscreen mode if already open

### ISSUE THREAD

**Issue by briandle00** [jarrettgilliam/AutoGame#8]
Is there any way to enable this to switch from desktop to fullscreen mode if Playnite is already running? I generally leave it in the background, so adding an extra step of having to quit out of it or disabling minimizing it when I close the window is a bit annoying.

**Comment by jarrettgilliam** [comment]
I hear you. Funny enough I [fixed](https://github.com/jarrettgilliam/AutoGame/commit/bf476111a78e90d44169d183e57d6034a272b15e) this the other day. Playnite has a built in command line argument for this called [--startfullscreen](https://playnite.link/docs/manual/cmdlineArguments.html). It will be in the next release (which should be out soon).

**Comment by briandle00** [comment]
Good to hear -- I'll buy you a coffee when the release drops :)

**Comment by jarrettgilliam** [comment]
Fixed in v2.0.0
